FROM prom/prometheus:latest

# Copiar configuración
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Exponer puerto
EXPOSE 9090

# Comando por defecto
CMD ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/etc/prometheus/console_libraries", "--web.console.templates=/etc/prometheus/consoles", "--web.enable-lifecycle"]

